name: venturo_core
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  
  # UI
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

  change_app_package_name: ^1.1.0

  # Signature
  fast_rsa: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

